// Copyright (C) 2018 JackMyth. All Rights Reserved. 
// Code is generated by PreBuildSteps, Don't modify it directly, Use UIRec.txt instead. 
  
#pragma once
#include "CoreMinimal.h" 
#include "UObject/NoExportTypes.h" 
#include "Object.h"
#include "SubclassOf.h"
#include "UIProvider.generated.h" 
 
DECLARE_DYNAMIC_DELEGATE_OneParam(FPauseUIDelegate, TSubclassOf<class UPauseUIBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FDetailsListDelegate, TSubclassOf<class UDetailsListBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FDetailCategoryDelegate, TSubclassOf<class UDetailCategoryBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FDetailInputNumberDelegate, TSubclassOf<class UDetailInputNumberBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FDetailInputStringDelegate, TSubclassOf<class UDetailInputStringBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FEditorMainUIDelegate, TSubclassOf<class UEditorMainUIBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FEditorPanelDelegate, TSubclassOf<class UEditorPanelBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FInstructionWidgetDelegate, TSubclassOf<class UInstructionWidgetBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FGameUIDelegate, TSubclassOf<class UGameUIBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FGameResultUIDelegate, TSubclassOf<class UGameResultUIBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FWelcomeUIDelegate, TSubclassOf<class UWelcomeUIBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FMainMenuUIDelegate, TSubclassOf<class UMainMenuUIBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FScoreSelectionUIDelegate, TSubclassOf<class UScoreSelectionUIBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FGenericSelectionItemDelegate, TSubclassOf<class UGenericSelectionItemBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FMessageBoxDelegate, TSubclassOf<class UMessageBoxBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FQuestionBoxDelegate, TSubclassOf<class UQuestionBoxBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FDownloadItemDelegate, TSubclassOf<class UDownloadItemBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FUploadItemDelegate, TSubclassOf<class UUploadItemBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FDownloadListDelegate, TSubclassOf<class UDownloadListBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FContentManagerUIDelegate, TSubclassOf<class UContentManagerUIBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FMusicManagerUIDelegate, TSubclassOf<class UMusicManagerUIBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FScoreManagerUIDelegate, TSubclassOf<class UScoreManagerUIBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FModManagerUIDelegate, TSubclassOf<class UModManagerUIBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FMusicImportationUIDelegate, TSubclassOf<class UMusicImportationUIBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FScoreEditorEntryUIDelegate, TSubclassOf<class UScoreEditorEntryUIBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FInputBoxDelegate, TSubclassOf<class UInputBoxBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FDetailInputBoolDelegate, TSubclassOf<class UDetailInputBoolBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FRhythmWidgetDelegate, TSubclassOf<class URhythmWidgetBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FDetailInputColorDelegate, TSubclassOf<class UDetailInputColorBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FDetailInputSelectionDelegate, TSubclassOf<class UDetailInputSelectionBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FRhythmSlideWidgetDelegate, TSubclassOf<class URhythmSlideWidgetBase>&, _returnV);
 
/**Provide UI for modding,should get all UI from this class.**/  
UCLASS(NotBlueprintable)
class MUTHM_API UUIProvider : public UObject
{
	GENERATED_BODY()
public:
	UFUNCTION(BlueprintPure,DisplayName="Get UI Provider",meta=(WorldContext="WorldContextObj"))
	static UUIProvider* Get(const UObject* WorldContextObj);
 
	UPROPERTY(BlueprintReadWrite)
		FPauseUIDelegate PauseUI;
	UFUNCTION(BlueprintCallable)
		void ClearPauseUI() { PauseUI.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UPauseUIBase> GetPauseUI(); 
 
	UPROPERTY(BlueprintReadWrite)
		FDetailsListDelegate DetailsList;
	UFUNCTION(BlueprintCallable)
		void ClearDetailsList() { DetailsList.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UDetailsListBase> GetDetailsList(); 
 
	UPROPERTY(BlueprintReadWrite)
		FDetailCategoryDelegate DetailCategory;
	UFUNCTION(BlueprintCallable)
		void ClearDetailCategory() { DetailCategory.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UDetailCategoryBase> GetDetailCategory(); 
 
	UPROPERTY(BlueprintReadWrite)
		FDetailInputNumberDelegate DetailInputNumber;
	UFUNCTION(BlueprintCallable)
		void ClearDetailInputNumber() { DetailInputNumber.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UDetailInputNumberBase> GetDetailInputNumber(); 
 
	UPROPERTY(BlueprintReadWrite)
		FDetailInputStringDelegate DetailInputString;
	UFUNCTION(BlueprintCallable)
		void ClearDetailInputString() { DetailInputString.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UDetailInputStringBase> GetDetailInputString(); 
 
	UPROPERTY(BlueprintReadWrite)
		FEditorMainUIDelegate EditorMainUI;
	UFUNCTION(BlueprintCallable)
		void ClearEditorMainUI() { EditorMainUI.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UEditorMainUIBase> GetEditorMainUI(); 
 
	UPROPERTY(BlueprintReadWrite)
		FEditorPanelDelegate EditorPanel;
	UFUNCTION(BlueprintCallable)
		void ClearEditorPanel() { EditorPanel.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UEditorPanelBase> GetEditorPanel(); 
 
	UPROPERTY(BlueprintReadWrite)
		FInstructionWidgetDelegate InstructionWidget;
	UFUNCTION(BlueprintCallable)
		void ClearInstructionWidget() { InstructionWidget.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UInstructionWidgetBase> GetInstructionWidget(); 
 
	UPROPERTY(BlueprintReadWrite)
		FGameUIDelegate GameUI;
	UFUNCTION(BlueprintCallable)
		void ClearGameUI() { GameUI.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UGameUIBase> GetGameUI(); 
 
	UPROPERTY(BlueprintReadWrite)
		FGameResultUIDelegate GameResultUI;
	UFUNCTION(BlueprintCallable)
		void ClearGameResultUI() { GameResultUI.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UGameResultUIBase> GetGameResultUI(); 
 
	UPROPERTY(BlueprintReadWrite)
		FWelcomeUIDelegate WelcomeUI;
	UFUNCTION(BlueprintCallable)
		void ClearWelcomeUI() { WelcomeUI.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UWelcomeUIBase> GetWelcomeUI(); 
 
	UPROPERTY(BlueprintReadWrite)
		FMainMenuUIDelegate MainMenuUI;
	UFUNCTION(BlueprintCallable)
		void ClearMainMenuUI() { MainMenuUI.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UMainMenuUIBase> GetMainMenuUI(); 
 
	UPROPERTY(BlueprintReadWrite)
		FScoreSelectionUIDelegate ScoreSelectionUI;
	UFUNCTION(BlueprintCallable)
		void ClearScoreSelectionUI() { ScoreSelectionUI.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UScoreSelectionUIBase> GetScoreSelectionUI(); 
 
	UPROPERTY(BlueprintReadWrite)
		FGenericSelectionItemDelegate GenericSelectionItem;
	UFUNCTION(BlueprintCallable)
		void ClearGenericSelectionItem() { GenericSelectionItem.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UGenericSelectionItemBase> GetGenericSelectionItem(); 
 
	UPROPERTY(BlueprintReadWrite)
		FMessageBoxDelegate MessageBox;
	UFUNCTION(BlueprintCallable)
		void ClearMessageBox() { MessageBox.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UMessageBoxBase> GetMessageBox(); 
 
	UPROPERTY(BlueprintReadWrite)
		FQuestionBoxDelegate QuestionBox;
	UFUNCTION(BlueprintCallable)
		void ClearQuestionBox() { QuestionBox.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UQuestionBoxBase> GetQuestionBox(); 
 
	UPROPERTY(BlueprintReadWrite)
		FDownloadItemDelegate DownloadItem;
	UFUNCTION(BlueprintCallable)
		void ClearDownloadItem() { DownloadItem.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UDownloadItemBase> GetDownloadItem(); 
 
	UPROPERTY(BlueprintReadWrite)
		FUploadItemDelegate UploadItem;
	UFUNCTION(BlueprintCallable)
		void ClearUploadItem() { UploadItem.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UUploadItemBase> GetUploadItem(); 
 
	UPROPERTY(BlueprintReadWrite)
		FDownloadListDelegate DownloadList;
	UFUNCTION(BlueprintCallable)
		void ClearDownloadList() { DownloadList.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UDownloadListBase> GetDownloadList(); 
 
	UPROPERTY(BlueprintReadWrite)
		FContentManagerUIDelegate ContentManagerUI;
	UFUNCTION(BlueprintCallable)
		void ClearContentManagerUI() { ContentManagerUI.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UContentManagerUIBase> GetContentManagerUI(); 
 
	UPROPERTY(BlueprintReadWrite)
		FMusicManagerUIDelegate MusicManagerUI;
	UFUNCTION(BlueprintCallable)
		void ClearMusicManagerUI() { MusicManagerUI.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UMusicManagerUIBase> GetMusicManagerUI(); 
 
	UPROPERTY(BlueprintReadWrite)
		FScoreManagerUIDelegate ScoreManagerUI;
	UFUNCTION(BlueprintCallable)
		void ClearScoreManagerUI() { ScoreManagerUI.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UScoreManagerUIBase> GetScoreManagerUI(); 
 
	UPROPERTY(BlueprintReadWrite)
		FModManagerUIDelegate ModManagerUI;
	UFUNCTION(BlueprintCallable)
		void ClearModManagerUI() { ModManagerUI.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UModManagerUIBase> GetModManagerUI(); 
 
	UPROPERTY(BlueprintReadWrite)
		FMusicImportationUIDelegate MusicImportationUI;
	UFUNCTION(BlueprintCallable)
		void ClearMusicImportationUI() { MusicImportationUI.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UMusicImportationUIBase> GetMusicImportationUI(); 
 
	UPROPERTY(BlueprintReadWrite)
		FScoreEditorEntryUIDelegate ScoreEditorEntryUI;
	UFUNCTION(BlueprintCallable)
		void ClearScoreEditorEntryUI() { ScoreEditorEntryUI.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UScoreEditorEntryUIBase> GetScoreEditorEntryUI(); 
 
	UPROPERTY(BlueprintReadWrite)
		FInputBoxDelegate InputBox;
	UFUNCTION(BlueprintCallable)
		void ClearInputBox() { InputBox.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UInputBoxBase> GetInputBox(); 
 
	UPROPERTY(BlueprintReadWrite)
		FDetailInputBoolDelegate DetailInputBool;
	UFUNCTION(BlueprintCallable)
		void ClearDetailInputBool() { DetailInputBool.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UDetailInputBoolBase> GetDetailInputBool(); 
 
	UPROPERTY(BlueprintReadWrite)
		FRhythmWidgetDelegate RhythmWidget;
	UFUNCTION(BlueprintCallable)
		void ClearRhythmWidget() { RhythmWidget.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class URhythmWidgetBase> GetRhythmWidget(); 
 
	UPROPERTY(BlueprintReadWrite)
		FDetailInputColorDelegate DetailInputColor;
	UFUNCTION(BlueprintCallable)
		void ClearDetailInputColor() { DetailInputColor.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UDetailInputColorBase> GetDetailInputColor(); 
 
	UPROPERTY(BlueprintReadWrite)
		FDetailInputSelectionDelegate DetailInputSelection;
	UFUNCTION(BlueprintCallable)
		void ClearDetailInputSelection() { DetailInputSelection.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class UDetailInputSelectionBase> GetDetailInputSelection(); 
 
	UPROPERTY(BlueprintReadWrite)
		FRhythmSlideWidgetDelegate RhythmSlideWidget;
	UFUNCTION(BlueprintCallable)
		void ClearRhythmSlideWidget() { RhythmSlideWidget.Unbind(); }
	UFUNCTION(BlueprintPure)
		TSubclassOf<class URhythmSlideWidgetBase> GetRhythmSlideWidget(); 
 
}; 
