// Copyright (C) 2018 JackMyth. All Rights Reserved. 
// Code is generated by PreBuildSteps, Don't modify it directly, Use UIRec.txt instead. 
  
#include "CoreMinimal.h" 
#include "UObject/NoExportTypes.h" 
#include "UIProvider.generated.h" 
 
DECLARE_DYNAMIC_DELEGATE_OneParam(FPauseUIDelegate, TSubclassOf<class UPauseUIBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FDetailCategoryDelegate, TSubclassOf<class UDetailCategoryBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FDetailInputNumberDelegate, TSubclassOf<class UDetailInputNumberBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FDetailInputStringDelegate, TSubclassOf<class UDetailInputStringBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FEditorMainUIDelegate, TSubclassOf<class UEditorMainUIBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FEditorPanelDelegate, TSubclassOf<class UEditorPanelBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FInstructionWidgetDelegate, TSubclassOf<class UInstructionWidgetBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FGameUIDelegate, TSubclassOf<class UGameUIBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FGameResultUIDelegate, TSubclassOf<class UGameResultUIBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FWelcomeUIDelegate, TSubclassOf<class UWelcomeUIBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FMainMenuUIDelegate, TSubclassOf<class UMainMenuUIBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FScoreSelectionUIDelegate, TSubclassOf<class UScoreSelectionUIBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FGenericSelectionItemDelegate, TSubclassOf<class UGenericSelectionItemBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FMessageBoxDelegate, TSubclassOf<class UMessageBoxBase>&, _returnV);
DECLARE_DYNAMIC_DELEGATE_OneParam(FQuestionBoxDelegate, TSubclassOf<class UQuestionBoxBase>&, _returnV);
 
/**Provide UI for modding,should get all UI from this class.**/  
UCLASS(NotBlueprintable) 
class MUTHM_API UUIProvider : public UObject 
{
	GENERATED_BODY()
public:
	UFUNCTION(BlueprintPure,DisplayName="Get UI Provider") 
static UUIProvider* Get()
	{
	}
:echo static UUIProvider* Get()
	{
	}
:
	UPROPERTY(BlueprintReadWrite)
		FPauseUIDelegate PauseUI;
	UFUNCTION(BlueprintCallable)
		void ClearPauseUI() { PauseUI.Unbind(); }
	TSubclassOf<UPauseUIBase> GetPauseUI(); 
	UPROPERTY(BlueprintReadWrite)
		FDetailCategoryDelegate DetailCategory;
	UFUNCTION(BlueprintCallable)
		void ClearDetailCategory() { DetailCategory.Unbind(); }
	TSubclassOf<UDetailCategoryBase> GetDetailCategory(); 
	UPROPERTY(BlueprintReadWrite)
		FDetailInputNumberDelegate DetailInputNumber;
	UFUNCTION(BlueprintCallable)
		void ClearDetailInputNumber() { DetailInputNumber.Unbind(); }
	TSubclassOf<UDetailInputNumberBase> GetDetailInputNumber(); 
	UPROPERTY(BlueprintReadWrite)
		FDetailInputStringDelegate DetailInputString;
	UFUNCTION(BlueprintCallable)
		void ClearDetailInputString() { DetailInputString.Unbind(); }
	TSubclassOf<UDetailInputStringBase> GetDetailInputString(); 
	UPROPERTY(BlueprintReadWrite)
		FEditorMainUIDelegate EditorMainUI;
	UFUNCTION(BlueprintCallable)
		void ClearEditorMainUI() { EditorMainUI.Unbind(); }
	TSubclassOf<UEditorMainUIBase> GetEditorMainUI(); 
	UPROPERTY(BlueprintReadWrite)
		FEditorPanelDelegate EditorPanel;
	UFUNCTION(BlueprintCallable)
		void ClearEditorPanel() { EditorPanel.Unbind(); }
	TSubclassOf<UEditorPanelBase> GetEditorPanel(); 
	UPROPERTY(BlueprintReadWrite)
		FInstructionWidgetDelegate InstructionWidget;
	UFUNCTION(BlueprintCallable)
		void ClearInstructionWidget() { InstructionWidget.Unbind(); }
	TSubclassOf<UInstructionWidgetBase> GetInstructionWidget(); 
	UPROPERTY(BlueprintReadWrite)
		FGameUIDelegate GameUI;
	UFUNCTION(BlueprintCallable)
		void ClearGameUI() { GameUI.Unbind(); }
	TSubclassOf<UGameUIBase> GetGameUI(); 
	UPROPERTY(BlueprintReadWrite)
		FGameResultUIDelegate GameResultUI;
	UFUNCTION(BlueprintCallable)
		void ClearGameResultUI() { GameResultUI.Unbind(); }
	TSubclassOf<UGameResultUIBase> GetGameResultUI(); 
	UPROPERTY(BlueprintReadWrite)
		FWelcomeUIDelegate WelcomeUI;
	UFUNCTION(BlueprintCallable)
		void ClearWelcomeUI() { WelcomeUI.Unbind(); }
	TSubclassOf<UWelcomeUIBase> GetWelcomeUI(); 
	UPROPERTY(BlueprintReadWrite)
		FMainMenuUIDelegate MainMenuUI;
	UFUNCTION(BlueprintCallable)
		void ClearMainMenuUI() { MainMenuUI.Unbind(); }
	TSubclassOf<UMainMenuUIBase> GetMainMenuUI(); 
	UPROPERTY(BlueprintReadWrite)
		FScoreSelectionUIDelegate ScoreSelectionUI;
	UFUNCTION(BlueprintCallable)
		void ClearScoreSelectionUI() { ScoreSelectionUI.Unbind(); }
	TSubclassOf<UScoreSelectionUIBase> GetScoreSelectionUI(); 
	UPROPERTY(BlueprintReadWrite)
		FGenericSelectionItemDelegate GenericSelectionItem;
	UFUNCTION(BlueprintCallable)
		void ClearGenericSelectionItem() { GenericSelectionItem.Unbind(); }
	TSubclassOf<UGenericSelectionItemBase> GetGenericSelectionItem(); 
	UPROPERTY(BlueprintReadWrite)
		FMessageBoxDelegate MessageBox;
	UFUNCTION(BlueprintCallable)
		void ClearMessageBox() { MessageBox.Unbind(); }
	TSubclassOf<UMessageBoxBase> GetMessageBox(); 
	UPROPERTY(BlueprintReadWrite)
		FQuestionBoxDelegate QuestionBox;
	UFUNCTION(BlueprintCallable)
		void ClearQuestionBox() { QuestionBox.Unbind(); }
	TSubclassOf<UQuestionBoxBase> GetQuestionBox(); 
}; 
